import type { AdminQuizItem } from "./types"

function cloneAdminQuizItem(item: AdminQuizItem): AdminQuizItem {
  return {
    ...item,
    tags: [...item.tags],
    valuePoints: [...item.valuePoints],
    flowSteps: [...item.flowSteps],
    verification: item.verification
      ? {
          ...item.verification,
          sampleCodes: item.verification.sampleCodes.map((sampleCode) => ({ ...sampleCode })),
        }
      : undefined,
  }
}

const staticAdminQuizItems: AdminQuizItem[] = [
  {
    id: "free_quiz_aura_color",
    slug: "free/aura",
    title: "你的 Aura 是什么颜色？",
    category: "免费 / 灵魂气场",
    summary: "基于双维度四象限模型的免费体验测试，3 分钟快速识别你的灵魂底色。",
    tagline: "免费体验款，用于内容传播和引流。",
    priceLabel: "免费体验",
    durationMinutes: 3,
    questionCount: 18,
    accessSummary: "无需验证码，直接开始测试",
    tags: ["免费", "Aura", "18 题", "引流款"],
    valuePoints: ["8 种灵魂光谱", "专属灵魂画像", "可分享结果页"],
    flowSteps: ["进入页面", "完成 18 题", "查看结果"],
    status: "published",
    accessType: "free",
    source: "static",
    introPath: "/free/aura",
    testPath: "/free/aura/test",
    landingVisible: true,
    liveOnLanding: true,
  },
  {
    id: "free_quiz_banwei_density",
    slug: "free/banwei",
    title: "你的班味浓度检测",
    category: "免费 / 职场娱乐",
    summary: "面向打工人传播场景的免费检测题，用五维成分分析你的班味浓度。",
    tagline: "免费轻测款，用于社交传播和用户破冰。",
    priceLabel: "免费体验",
    durationMinutes: 2,
    questionCount: 15,
    accessSummary: "无需验证码，直接开始测试",
    tags: ["免费", "班味", "15 题", "传播测试"],
    valuePoints: ["五维成分分析", "社畜形态结论", "可分享医嘱单"],
    flowSteps: ["进入页面", "完成 15 题", "查看结果"],
    status: "published",
    accessType: "free",
    source: "static",
    introPath: "/free/banwei",
    testPath: "/free/banwei/test",
    landingVisible: true,
    liveOnLanding: true,
  },
  {
    id: "free_quiz_painting_soul_map",
    slug: "free/painting",
    title: "你的灵魂是哪幅名画？",
    category: "免费 / 艺术人格",
    summary: "通过 28 道审美与直觉选择题，定位你的艺术人格坐标。",
    tagline: "免费艺术人格测试，适合做传播和风格种草。",
    priceLabel: "免费体验",
    durationMinutes: 5,
    questionCount: 28,
    accessSummary: "无需验证码，直接开始测试",
    tags: ["免费", "名画", "28 题", "艺术人格"],
    valuePoints: ["艺术风格匹配", "人格投射结果", "结果页可分享"],
    flowSteps: ["进入页面", "完成 28 题", "查看结果"],
    status: "published",
    accessType: "free",
    source: "static",
    introPath: "/free/painting",
    testPath: "/free/painting/test",
    landingVisible: true,
    liveOnLanding: true,
  },
  {
    id: "free_quiz_hidden_talent",
    slug: "free/talent",
    title: "你的隐藏天赋是什么？",
    category: "免费 / 天赋探索",
    summary: "基于六维天赋模型的轻量测试，帮助用户快速看见自己的核心优势。",
    tagline: "免费天赋测试，适合首轮破冰和用户分享。",
    priceLabel: "免费体验",
    durationMinutes: 3,
    questionCount: 20,
    accessSummary: "无需验证码，直接开始测试",
    tags: ["免费", "天赋", "20 题", "热门推荐"],
    valuePoints: ["六维天赋画像", "天赋原型判断", "结果页可分享"],
    flowSteps: ["进入页面", "完成 20 题", "查看结果"],
    status: "published",
    accessType: "free",
    source: "static",
    introPath: "/free/talent",
    testPath: "/free/talent/test",
    landingVisible: true,
    liveOnLanding: true,
  },
  {
    id: "free_quiz_szondi_shadow",
    slug: "free/szondi",
    title: "索迪测试：潜意识暗影",
    category: "免费 / 潜意识投射",
    summary: "基于经典投射法的免费测试，用影像偏好揭示你更容易压抑的那一面。",
    tagline: "免费暗影探索，适合作为轻量传播款。",
    priceLabel: "免费体验",
    durationMinutes: 4,
    questionCount: 24,
    accessSummary: "无需验证码，直接开始测试",
    tags: ["免费", "索迪", "24 题", "暗影探索"],
    valuePoints: ["潜意识偏好", "隐藏冲动提示", "结果页可分享"],
    flowSteps: ["进入页面", "完成 24 题", "查看结果"],
    status: "published",
    accessType: "free",
    source: "static",
    introPath: "/free/szondi",
    testPath: "/free/szondi/test",
    landingVisible: true,
    liveOnLanding: true,
  },
  {
    id: "free_quiz_soul_city",
    slug: "free/soul-city",
    title: "你的灵魂是哪座城市？",
    category: "免费 / 城市人格",
    summary: "把大五人格映射到城市气质，用 30 道轻量题找到最像你的世界坐标。",
    tagline: "免费城市人格测试，适合社交分享和世界观种草。",
    priceLabel: "免费体验",
    durationMinutes: 4,
    questionCount: 30,
    accessSummary: "无需验证码，直接开始测试",
    tags: ["免费", "城市人格", "30 题", "分享向"],
    valuePoints: ["五维灵魂匹配", "18 座全球城市", "结果页可分享"],
    flowSteps: ["进入页面", "完成 30 题", "查看结果"],
    status: "published",
    accessType: "free",
    source: "static",
    introPath: "/free/soul-city",
    testPath: "/free/soul-city/test",
    landingVisible: true,
    liveOnLanding: true,
  },
  {
    id: "quiz_bigfive_personality",
    slug: "bigfive",
    title: "大五人格测试",
    category: "人格 / 性格",
    summary: "基于国际通用 Big Five 模型的大五人格测试，帮助你看到自己在五个核心维度上的稳定偏好。",
    tagline: "50 题正式版，支持保存人格画像与结果长图。",
    priceLabel: "50 题正式版",
    durationMinutes: 8,
    questionCount: 50,
    accessSummary: "输入购买后获得的验证码开始测试，有效期内可重复进入",
    tags: ["付费", "大五人格", "50 题"],
    valuePoints: ["五维人格画像", "关系 / 工作 / 压力解读", "支持保存与分享"],
    flowSteps: ["输入验证码", "完成 50 题", "查看完整结果"],
    status: "published",
    accessType: "paid",
    source: "static",
    introPath: "/bigfive",
    testPath: "/bigfive/test",
    landingVisible: true,
    liveOnLanding: true,
  },
  {
    id: "quiz_oejts_personality_map",
    slug: "oejts-personality-map",
    title: "OEJTS 16 型人格图谱",
    category: "人格 / 性格",
    summary: "OEJTS 16 型人格图谱是一套基于四条人格偏好维度的自我探索测试，帮助用户理解自己的注意力方向、判断方式与行动节奏。",
    tagline: "正式版首发，结果页支持回看、保存与分享。",
    priceLabel: "32 题正式版",
    durationMinutes: 8,
    questionCount: 32,
    accessSummary: "输入验证码后开始测试，有效期内可重复进入",
    tags: ["付费", "OEJTS", "32 题"],
    valuePoints: ["16 型结果", "四维偏好解读", "支持长图导出"],
    flowSteps: ["输入验证码", "完成 32 题", "查看完整结果"],
    status: "published",
    accessType: "paid",
    source: "static",
    introPath: "/oejts-personality-map",
    testPath: "/oejts-personality-map/test",
    landingVisible: true,
    liveOnLanding: true,
  },
  {
    id: "quiz_relationship_preference_test",
    slug: "relationship-preference-test",
    title: "亲密关系偏好测试",
    category: "关系 / 亲密关系",
    summary: "基于五种爱情语言模型改编的付费正式版测试，用来识别用户在亲密关系中最敏感的被爱方式与错位点。",
    tagline: "30 题正式版，支持结果回看、分享和关系海报导出。",
    priceLabel: "30 题正式版",
    durationMinutes: 6,
    questionCount: 30,
    accessSummary: "输入购买后获得的验证码开始测试，有效期内可重复进入",
    tags: ["付费", "亲密关系", "30 题"],
    valuePoints: ["主语言 / 次语言判断", "五维分布", "伴侣行动建议"],
    flowSteps: ["输入验证码", "完成 30 题", "查看完整结果"],
    status: "published",
    accessType: "paid",
    source: "static",
    introPath: "/relationship-preference-test",
    testPath: "/relationship-preference-test/test",
    landingVisible: true,
    liveOnLanding: true,
  },
  {
    id: "quiz_enneagram_54",
    slug: "enneagram",
    title: "九型人格测试",
    category: "人格 / 驱动力",
    summary: "从核心驱动力切入的付费正式版测试，54 道原创中文题帮助用户看见自己最接近哪一型，以及关系、工作与压力下的自然模式。",
    tagline: "54 题正式版，结果页支持保存驱动力长图与社媒分享。",
    priceLabel: "54 题正式版",
    durationMinutes: 9,
    questionCount: 54,
    accessSummary: "输入购买后获得的验证码开始测试，有效期内可重复进入",
    tags: ["付费", "九型人格", "54 题"],
    valuePoints: ["主型 + 近邻类型判断", "关系 / 工作 / 压力解析", "支持长图导出"],
    flowSteps: ["输入验证码", "完成 54 题", "查看完整结果"],
    status: "published",
    accessType: "paid",
    source: "static",
    introPath: "/enneagram",
    testPath: "/enneagram/test",
    landingVisible: true,
    liveOnLanding: true,
  },
  {
    id: "quiz_dark_triad",
    slug: "dark-triad",
    title: "暗面力量测试",
    category: "专业量表",
    summary: "每个人都有不愿意承认的那一面。基于经典的暗黑三角模型，这套测试将帮你看见隐藏在人格深处的策略操盘、聚光主场与冷感冒险倾向。",
    tagline: "27 题专业版，探索你的暗面人格与生存策略。",
    priceLabel: "27 题正式版",
    durationMinutes: 5,
    questionCount: 27,
    accessSummary: "输入购买后获得的验证码开始测试，有效期内可重复进入",
    tags: ["付费", "暗面人格", "27 题"],
    valuePoints: ["三维人格分布图", "9 大暗面原型定位", "人际与竞争策略拆解"],
    flowSteps: ["输入验证码", "完成 27 题自评", "解锁深度报告"],
    status: "published",
    accessType: "paid",
    source: "static",
    introPath: "/dark-triad",
    testPath: "/dark-triad/test",
    landingVisible: true,
    liveOnLanding: true,
  },
  {
    id: "quiz_hexaco_personality",
    slug: "hexaco-60",
    title: "HEXACO 六维人格测试",
    category: "人格 / 性格",
    summary:
      "基于 HEXACO 六维人格模型，通过 60 道题目深度还原你在规则、情绪、社交、冲突、执行与开放性六个维度上的稳定偏好。比大五人格多一维，看见更真实的自己。",
    tagline: "60 题专业版，支持结果回看、分享与一键导出六维雷达图海报。",
    priceLabel: "60 题正式版",
    durationMinutes: 10,
    questionCount: 60,
    accessSummary: "输入购买后获得的验证码开始测试，有效期内可重复进入",
    tags: ["HEXACO", "六维人格", "60 题", "深度解析"],
    valuePoints: ["六维人格图谱", "H 维度特色解读", "关系 / 协作 / 压力全景报告"],
    flowSteps: ["输入验证码", "完成 60 题", "查看完整结果"],
    status: "published",
    accessType: "paid",
    source: "static",
    introPath: "/hexaco-60",
    testPath: "/hexaco-60/test",
    landingVisible: true,
    liveOnLanding: true,
  },
  {
    id: "quiz_soul_tarot",
    slug: "soul-tarot",
    title: "你是哪张塔罗牌？",
    category: "神秘学 / 心理",
    summary: "22 张大阿尔卡纳，22 种灵魂原型——你的灵魂，对应哪一张牌？基于 5 维向量匹配算法，寻找你的灵魂归宿。",
    tagline: "30 题正式版，支持一键导出精美塔罗灵魂海报。",
    priceLabel: "30 题正式版",
    durationMinutes: 10,
    questionCount: 30,
    accessSummary: "输入购买后获得的验证码开始测试，有效期内可重复进入",
    tags: ["付费", "塔罗", "30 题"],
    valuePoints: ["灵魂塔罗匹配", "五维灵魂向量", "灵魂判词与生活建议"],
    flowSteps: ["输入验证码", "完成 30 题", "揭开灵魂牌面"],
    status: "published",
    accessType: "paid",
    source: "static",
    introPath: "/soul-tarot",
    testPath: "/soul-tarot/test",
    landingVisible: true,
    liveOnLanding: true,
  },
  {
    id: "quiz_riasec_48",
    slug: "riasec-48",
    title: "霍兰德 RIASEC 职业兴趣测试",
    category: "职业 / 发展",
    summary: "基于经典 Holland RIASEC 模型，通过 48 道精选题目，精准还原你在六个核心维度上的兴趣偏好，帮你找到更契合的工作环境与职业方向。",
    tagline: "48 题正式版，包含 12 组深度三码报告与六维图谱。",
    priceLabel: "48 题正式版",
    durationMinutes: 8,
    questionCount: 48,
    accessSummary: "输入购买后获得的验证码开始测试，有效期内可重复进入",
    tags: ["职业兴趣", "RIASEC", "48 题", "深度解析"],
    valuePoints: ["六维兴趣图谱", "前三码深度报告", "适合的任务与环境建议"],
    flowSteps: ["输入验证码", "完成 48 题", "查看完整结果"],
    status: "published",
    accessType: "paid",
    source: "static",
    introPath: "/riasec-48",
    testPath: "/riasec-48/test",
    landingVisible: true,
    liveOnLanding: true,
  },
  {
    id: "quiz_stress_load_test",
    slug: "stress-load-test",
    title: "压力负荷测试",
    category: "心理状态 / 压力",
    summary: "测测最近 30 天，你的心理系统到底承受了多少重量",
    tagline: "25 题专业版，深度解读你的心理负荷与恢复系统。",
    priceLabel: "25 题正式版",
    durationMinutes: 5,
    questionCount: 25,
    accessSummary: "输入购买后获得的验证码开始测试，有效期内可重复进入",
    tags: ["压力负荷", "25 题", "心理状态", "深度报告"],
    valuePoints: ["五维压力负荷图谱", "主导压力来源画像", "72 小时减压行动卡"],
    flowSteps: ["输入验证码", "完成 25 题自评", "解锁深度报告"],
    status: "published",
    accessType: "paid",
    source: "static",
    introPath: "/stress-load-test",
    testPath: "/stress-load-test",
    landingVisible: true,
    liveOnLanding: true,
  },
  {
    id: "quiz_desire_composition",
    slug: "desire-composition",
    title: "你的欲望组成图",
    category: "性格探索 / 欲望",
    summary: "每个人心中都藏着一份欲望配方，测测你的灵魂最渴望什么",
    tagline: "12 题正式版，生成你的专属欲望饼图与欲望人格标签。",
    priceLabel: "12 题正式版",
    durationMinutes: 2,
    questionCount: 12,
    accessSummary: "输入购买后获得的验证码开始测试，有效期内可重复进入",
    tags: ["欲望组成", "12 题", "饼图", "人格标签"],
    valuePoints: ["七维欲望饼图", "欲望人格标签", "全国对比数据", "精美长图导出"],
    flowSteps: ["输入验证码", "完成 12 题情景选择", "生成欲望组成图"],
    status: "published",
    accessType: "paid",
    source: "static",
    introPath: "/desire-composition",
    testPath: "/desire-composition",
    landingVisible: true,
    liveOnLanding: true,
  },
]

const mockOnlyPaidQuizItems: AdminQuizItem[] = [
  {
    ...staticAdminQuizItems.find((item) => item.slug === "dark-triad")!,
    source: "mock",
    verification: {
      verificationMode: "shared_code",
      scopeMode: "product",
      batchStrategyType: "bundle",
      tokenTtlDays: 30,
      notes: "当前采用共享验证码，同一组验证码可同时进入大五人格与暗面力量测试。",
      batchName: "人格深测双题通用批次",
      batchStatus: "active",
      activeCodeCount: 4,
      sampleCodes: [
        { code: "SOUL-PRO-2026", status: "active", expiresAt: "2026-12-31T23:59:59.000Z" },
        { code: "ST-PRO-BETA", status: "active", expiresAt: "2026-12-31T23:59:59.000Z" },
        { code: "SD3-DARK-TRIAD", status: "active", expiresAt: "2026-12-31T23:59:59.000Z" },
      ],
    },
  },
  {
    ...staticAdminQuizItems.find((item) => item.slug === "oejts-personality-map")!,
    source: "mock",
    verification: {
      verificationMode: "shared_code",
      scopeMode: "product",
      batchStrategyType: "single_product",
      tokenTtlDays: 30,
      notes: "MVP 阶段使用单题通用验证码，后续可切换到一单一码。",
      batchName: "OEJTS 主售卖批次",
      batchStatus: "active",
      activeCodeCount: 2,
      sampleCodes: [
        { code: "SOUL-OEJTS-0313", status: "active", expiresAt: "2026-12-31T23:59:59.000Z" },
        { code: "ST-DEMO-ALPHA", status: "active", expiresAt: "2026-12-31T23:59:59.000Z" },
      ],
    },
  },
  {
    ...staticAdminQuizItems.find((item) => item.slug === "relationship-preference-test")!,
    source: "mock",
    verification: {
      verificationMode: "shared_code",
      scopeMode: "product",
      batchStrategyType: "single_product",
      tokenTtlDays: 30,
      notes: "当前采用随机通用验证码交付，便于首发验证市场。",
      batchName: "亲密关系偏好测试首发批次",
      batchStatus: "active",
      activeCodeCount: 2,
      sampleCodes: [
        { code: "RPREF-8Q4M-2T7K", status: "active", expiresAt: "2026-12-31T23:59:59.000Z" },
        { code: "ST-LOVE-BETA", status: "active", expiresAt: "2026-12-31T23:59:59.000Z" },
      ],
    },
  },
  {
    ...staticAdminQuizItems.find((item) => item.slug === "enneagram")!,
    source: "mock",
    verification: {
      verificationMode: "shared_code",
      scopeMode: "product",
      batchStrategyType: "single_product",
      tokenTtlDays: 30,
      notes: "九型人格首发阶段采用共享验证码，便于小红书投放和客服联调。",
      batchName: "九型人格首发批次",
      batchStatus: "active",
      activeCodeCount: 2,
      sampleCodes: [
        { code: "ENNEA-5W4-2026", status: "active", expiresAt: "2026-12-31T23:59:59.000Z" },
        { code: "ST-ENNEA-BETA", status: "active", expiresAt: "2026-12-31T23:59:59.000Z" },
      ],
    },
  },
  {
    ...staticAdminQuizItems.find((item) => item.slug === "bigfive")!,
    source: "mock",
    verification: {
      verificationMode: "shared_code",
      scopeMode: "product",
      batchStrategyType: "bundle",
      tokenTtlDays: 30,
      notes: "当前采用共享验证码，同一组验证码可同时进入大五人格与暗面力量测试。",
      batchName: "人格深测双题通用批次",
      batchStatus: "active",
      activeCodeCount: 4,
      sampleCodes: [
        { code: "SOUL-PRO-2026", status: "active", expiresAt: "2026-12-31T23:59:59.000Z" },
        { code: "ST-PRO-BETA", status: "active", expiresAt: "2026-12-31T23:59:59.000Z" },
        { code: "SD3-DARK-TRIAD", status: "active", expiresAt: "2026-12-31T23:59:59.000Z" },
      ],
    },
  },
  {
    ...staticAdminQuizItems.find((item) => item.slug === "soul-tarot")!,
    source: "mock",
    verification: {
      verificationMode: "shared_code",
      scopeMode: "product",
      batchStrategyType: "single_product",
      tokenTtlDays: 30,
      notes: "小红书主打灵魂塔罗测试共享验证码。",
      batchName: "灵魂塔罗首发批次",
      batchStatus: "active",
      activeCodeCount: 2,
      sampleCodes: [
        { code: "SOUL-TAROT-2026", status: "active", expiresAt: "2026-12-31T23:59:59.000Z" },
        { code: "ST-TAROT-BETA", status: "active", expiresAt: "2026-12-31T23:59:59.000Z" },
      ],
    },
  },
  {
    ...staticAdminQuizItems.find((item) => item.slug === "stress-load-test")!,
    source: "mock",
    verification: {
      verificationMode: "shared_code",
      scopeMode: "product",
      batchStrategyType: "single_product",
      tokenTtlDays: 30,
      notes: "压力负荷测试正式版共享验证码。",
      batchName: "压力负荷测试首发批次",
      batchStatus: "active",
      activeCodeCount: 2,
      sampleCodes: [
        { code: "STRESS-LOAD-2026", status: "active", expiresAt: "2026-12-31T23:59:59.000Z" },
        { code: "ST-STRESS-BETA", status: "active", expiresAt: "2026-12-31T23:59:59.000Z" },
      ],
    },
  },
  {
    ...staticAdminQuizItems.find((item) => item.slug === "desire-composition")!,
    source: "mock",
    verification: {
      verificationMode: "shared_code",
      scopeMode: "product",
      batchStrategyType: "single_product",
      tokenTtlDays: 30,
      notes: "欲望组成图首发阶段采用共享验证码，便于小红书投放。",
      batchName: "欲望组成图首发批次",
      batchStatus: "active",
      activeCodeCount: 2,
      sampleCodes: [
        { code: "DESIRE-COMP-2026", status: "active", expiresAt: "2026-12-31T23:59:59.000Z" },
        { code: "ST-DESIRE-BETA", status: "active", expiresAt: "2026-12-31T23:59:59.000Z" },
      ],
    },
  },
]

export function getStaticAdminQuizzes() {
  return staticAdminQuizItems.map(cloneAdminQuizItem)
}

export function getMockAdminQuizzes() {
  return [
    ...staticAdminQuizItems.filter((item) => item.accessType === "free").map(cloneAdminQuizItem),
    ...mockOnlyPaidQuizItems.map(cloneAdminQuizItem),
  ]
}

