import type { AdminQuizItem } from "./types"

const freeAdminQuizItems: AdminQuizItem[] = [
  {
    id: "free_quiz_aura_color",
    slug: "free/aura",
    title: "你的 Aura 是什么颜色？",
    category: "免费 / 灵魂气场",
    summary: "基于双维度四象限模型的免费体验测试，3 分钟快速识别你的灵魂底色。",
    tagline: "免费体验款，用于内容传播和引流。",
    priceLabel: "免费体验",
    durationMinutes: 3,
    questionCount: 18,
    accessSummary: "无需验证码，直接开始测试",
    tags: ["免费", "Aura", "18 题", "引流款"],
    valuePoints: ["8 种灵魂光谱", "专属灵魂画像", "可分享结果页"],
    flowSteps: ["进入页面", "完成 18 题", "查看结果"],
    status: "published",
    accessType: "free",
    source: "static",
    introPath: "/free/aura",
    testPath: "/free/aura/test",
  },
  {
    id: "free_quiz_banwei_density",
    slug: "free/banwei",
    title: "你的班味浓度检测",
    category: "免费 / 职场娱乐",
    summary: "面向打工人传播场景的免费检测题，用五维成分分析你的班味浓度。",
    tagline: "免费轻测款，用于社交传播和用户破冰。",
    priceLabel: "免费体验",
    durationMinutes: 2,
    questionCount: 15,
    accessSummary: "无需验证码，直接开始测试",
    tags: ["免费", "班味", "15 题", "传播测试"],
    valuePoints: ["五维成分分析", "社畜形态结论", "可分享医嘱单"],
    flowSteps: ["进入页面", "完成 15 题", "查看结果"],
    status: "published",
    accessType: "free",
    source: "static",
    introPath: "/free/banwei",
    testPath: "/free/banwei/test",
  },
]

const paidAdminQuizItems: AdminQuizItem[] = [
  {
    id: "quiz_oejts_personality_map",
    slug: "oejts-personality-map",
    title: "OEJTS 16 型人格图谱",
    category: "人格 / 性格",
    summary: "OEJTS 16 型人格图谱是一套基于四条人格偏好维度的自我探索测试，帮助用户理解自己的注意力方向、判断方式与行动节奏。",
    tagline: "正式版首发，结果页支持回看、保存与分享。",
    priceLabel: "32 题正式版",
    durationMinutes: 8,
    questionCount: 32,
    accessSummary: "输入验证码后开始测试，有效期内可重复进入",
    tags: ["付费", "OEJTS", "32 题"],
    valuePoints: ["16 型结果", "四维偏好解读", "支持长图导出"],
    flowSteps: ["输入验证码", "完成 32 题", "查看完整结果"],
    status: "published",
    accessType: "paid",
    source: "mock",
    introPath: "/oejts-personality-map",
    testPath: "/oejts-personality-map/test",
    verification: {
      verificationMode: "shared_code",
      scopeMode: "product",
      batchStrategyType: "single_product",
      tokenTtlDays: 30,
      notes: "MVP 阶段使用单题通用验证码，后续可切换到一单一码。",
      batchName: "OEJTS 主售卖批次",
      batchStatus: "active",
      activeCodeCount: 2,
      sampleCodes: [
        {
          code: "SOUL-OEJTS-0313",
          status: "active",
          expiresAt: "2026-12-31T23:59:59.000Z",
        },
        {
          code: "ST-DEMO-ALPHA",
          status: "active",
          expiresAt: "2026-12-31T23:59:59.000Z",
        },
      ],
    },
  },
  {
    id: "quiz_relationship_preference_test",
    slug: "relationship-preference-test",
    title: "亲密关系偏好测试",
    category: "关系 / 亲密关系",
    summary: "基于五种爱情语言模型改编的付费正式版测试，用来识别用户在亲密关系中最敏感的被爱方式与错位点。",
    tagline: "30 题正式版，支持结果回看、分享和关系海报导出。",
    priceLabel: "30 题正式版",
    durationMinutes: 6,
    questionCount: 30,
    accessSummary: "输入购买后获得的验证码开始测试，有效期内可重复进入",
    tags: ["付费", "亲密关系", "30 题"],
    valuePoints: ["主语言/次语言判断", "五维分布", "伴侣行动建议"],
    flowSteps: ["输入验证码", "完成 30 题", "查看完整结果"],
    status: "published",
    accessType: "paid",
    source: "mock",
    introPath: "/relationship-preference-test",
    testPath: "/relationship-preference-test/test",
    verification: {
      verificationMode: "shared_code",
      scopeMode: "product",
      batchStrategyType: "single_product",
      tokenTtlDays: 30,
      notes: "当前采用随机通用验证码交付，便于首发验证市场。",
      batchName: "亲密关系偏好测试首发批次",
      batchStatus: "active",
      activeCodeCount: 2,
      sampleCodes: [
        {
          code: "RPREF-8Q4M-2T7K",
          status: "active",
          expiresAt: "2026-12-31T23:59:59.000Z",
        },
        {
          code: "ST-LOVE-BETA",
          status: "active",
          expiresAt: "2026-12-31T23:59:59.000Z",
        },
      ],
    },
  },
]

export function getMockAdminQuizzes() {
  return [...freeAdminQuizItems, ...paidAdminQuizItems]
}
