import type { QuizRuntimeConfig } from "./types"

export const bigFiveRuntime: QuizRuntimeConfig = {
  meta: {
    slug: "bigfive",
    title: "大五人格测试",
    summary: "基于国际心理学界最权威的Big Five模型，50道精选题目精准还原你在外向性、宜人性、尽责性、神经质、开放性五个维度上的稳定偏好。",
    estimatedMinutes: 8,
    tags: ["大五人格", "50 题", "五维人格", "适合保存结果卡片"],
    category: "人格 / 性格",
  },
  runtime: {
    rendererKey: "generic",
    resultTemplateKey: "bigfive-profile",
    scoringKey: "bigfive",
  },
  presentation: {
    themeKey: "ink-glow",
    storyMode: true,
    screenCount: 5,
    shareCardKey: "bigfive-profile-poster",
  },
  questions: [
    { id: "Q01", chapter: 1, title: "我很容易主动打开话题，和别人聊起来。", trait: "E", reverse: false },
    { id: "Q02", chapter: 1, title: "我会真心在意别人的感受。", trait: "A", reverse: false },
    { id: "Q03", chapter: 1, title: "我做事通常会提前安排，不太临时抱佛脚。", trait: "C", reverse: false },
    { id: "Q04", chapter: 1, title: "我很容易因为压力而紧绷起来。", trait: "N", reverse: false },
    { id: "Q05", chapter: 1, title: "我常会被新奇的观点、作品或体验吸引。", trait: "O", reverse: false },
    { id: "Q06", chapter: 1, title: "我更习惯安静待着，不太主动出头。", trait: "E", reverse: true },
    { id: "Q07", chapter: 1, title: "我对陌生人的处境通常没什么兴趣。", trait: "A", reverse: true },
    { id: "Q08", chapter: 1, title: "我经常把东西随手一放，之后再到处找。", trait: "C", reverse: true },
    { id: "Q09", chapter: 1, title: "大多数时候，我的情绪都比较稳定放松。", trait: "N", reverse: true },
    { id: "Q10", chapter: 1, title: "抽象、概念化的话题常让我提不起兴趣。", trait: "O", reverse: true },
    { id: "Q11", chapter: 2, title: "和人相处时，我能给人比较有活力的感觉。", trait: "E", reverse: false },
    { id: "Q12", chapter: 2, title: "我能比较快察觉到别人情绪上的变化。", trait: "A", reverse: false },
    { id: "Q13", chapter: 2, title: "我做事会注意细节，不太容易漏项。", trait: "C", reverse: false },
    { id: "Q14", chapter: 2, title: "我常常会为还没发生的事提前担心。", trait: "N", reverse: false },
    { id: "Q15", chapter: 2, title: "我脑子里经常会冒出一些新点子。", trait: "O", reverse: false },
    { id: "Q16", chapter: 2, title: "在群体里，我通常不太爱成为焦点。", trait: "E", reverse: true },
    { id: "Q17", chapter: 2, title: "我说话有时会太冲，容易让人不舒服。", trait: "A", reverse: true },
    { id: "Q18", chapter: 2, title: "我的桌面、文件或生活物品经常比较乱。", trait: "C", reverse: true },
    { id: "Q19", chapter: 2, title: "我很少长时间陷在低落情绪里。", trait: "N", reverse: true },
    { id: "Q20", chapter: 2, title: "我不太喜欢讨论\"为什么\"或\"可能性\"这类问题。", trait: "O", reverse: true },
    { id: "Q21", chapter: 3, title: "我能把自己的热情传递给周围的人。", trait: "E", reverse: false },
    { id: "Q22", chapter: 3, title: "别人遇到难处时，我通常愿意站在对方角度想想。", trait: "A", reverse: false },
    { id: "Q23", chapter: 3, title: "我会把该做的事尽快做掉，而不是一直拖着。", trait: "C", reverse: false },
    { id: "Q24", chapter: 3, title: "一点小波动也可能让我心情受影响。", trait: "N", reverse: false },
    { id: "Q25", chapter: 3, title: "我有比较丰富的想象力。", trait: "O", reverse: false },
    { id: "Q26", chapter: 3, title: "面对陌生环境，我通常会先观察，不会马上融进去。", trait: "E", reverse: true },
    { id: "Q27", chapter: 3, title: "我有时会用刻薄的话去顶别人。", trait: "A", reverse: true },
    { id: "Q28", chapter: 3, title: "我常忘记把用完的东西放回原位。", trait: "C", reverse: true },
    { id: "Q29", chapter: 3, title: "遇到烦心事时，我通常恢复得还算快。", trait: "N", reverse: true },
    { id: "Q30", chapter: 3, title: "纯理论或太抽象的内容，我往往觉得无聊。", trait: "O", reverse: true },
    { id: "Q31", chapter: 4, title: "我在社交场合通常比较自在，也愿意接触人。", trait: "E", reverse: false },
    { id: "Q32", chapter: 4, title: "我愿意花时间理解别人为什么会那样想。", trait: "A", reverse: false },
    { id: "Q33", chapter: 4, title: "我喜欢有条理、按步骤地推进事情。", trait: "C", reverse: false },
    { id: "Q34", chapter: 4, title: "我很容易因为一时不顺而烦躁起来。", trait: "N", reverse: false },
    { id: "Q35", chapter: 4, title: "我常会停下来思考自己、关系或世界本身。", trait: "O", reverse: false },
    { id: "Q36", chapter: 4, title: "如果不是必要，我不会主动表现自己。", trait: "E", reverse: true },
    { id: "Q37", chapter: 4, title: "我有时显得有点冷淡，不太顾及别人感受。", trait: "A", reverse: true },
    { id: "Q38", chapter: 4, title: "我会逃避或拖延那些本该由我负责的事。", trait: "C", reverse: true },
    { id: "Q39", chapter: 4, title: "我的情绪起伏有时会比较明显。", trait: "N", reverse: false },
    { id: "Q40", chapter: 4, title: "我不太觉得自己是一个有创意的人。", trait: "O", reverse: true },
    { id: "Q41", chapter: 5, title: "我整体上是一个行动感比较强的人。", trait: "E", reverse: false },
    { id: "Q42", chapter: 5, title: "我通常能让周围的人感觉相处起来比较轻松。", trait: "A", reverse: false },
    { id: "Q43", chapter: 5, title: "我会按照计划或时间节点推进任务。", trait: "C", reverse: false },
    { id: "Q44", chapter: 5, title: "我很容易被冒犯，也容易因此不开心。", trait: "N", reverse: false },
    { id: "Q45", chapter: 5, title: "我理解新概念、新模型通常比较快。", trait: "O", reverse: false },
    { id: "Q46", chapter: 5, title: "比起热闹场面，我更偏向克制、内收的表达方式。", trait: "E", reverse: true },
    { id: "Q47", chapter: 5, title: "我愿意为别人腾出时间，而不是只顾自己安排。", trait: "A", reverse: false },
    { id: "Q48", chapter: 5, title: "我对自己的工作成果要求通常比较高。", trait: "C", reverse: false },
    { id: "Q49", chapter: 5, title: "我常常会莫名感到情绪低沉。", trait: "N", reverse: false },
    { id: "Q50", chapter: 5, title: "我喜欢探索不同角度，而不是只接受一种标准答案。", trait: "O", reverse: false },
  ],
  results: [
    {
      key: "bigfive-result",
      title: "大五人格测试结果",
      summary: "基于五维人格特质的深度解析",
    }
  ],
}
