import type { QuizRuntimeConfig, QuizResultDefinition } from "./types"

const ENNEAGRAM_SCALE = [
  "非常不符合",
  "比较不符合",
  "一般",
  "比较符合",
  "非常符合",
] as const

const ENNEAGRAM_DIMENSIONS = [
  { key: "1", label: "1 型改革者" },
  { key: "2", label: "2 型助人者" },
  { key: "3", label: "3 型成就者" },
  { key: "4", label: "4 型个性者" },
  { key: "5", label: "5 型观察者" },
  { key: "6", label: "6 型忠诚者" },
  { key: "7", label: "7 型热情者" },
  { key: "8", label: "8 型挑战者" },
  { key: "9", label: "9 型和平者" },
] as const

const enneagramQuestionBank = [
  { id: "q01", typeCode: "1", title: "我很难对明显的错误、低标准或敷衍了事视而不见。" },
  { id: "q02", typeCode: "2", title: "我习惯先察觉别人的需要，再考虑自己的状态。" },
  { id: "q03", typeCode: "3", title: "我希望自己在别人眼里是高效、优秀、拿得出手的。" },
  { id: "q04", typeCode: "4", title: "我很在意自己有没有活成一个真实而独特的人。" },
  { id: "q05", typeCode: "5", title: "我需要足够多的独处时间和心理空间。" },
  { id: "q06", typeCode: "6", title: "在做决定前，我通常会先想想哪里可能出问题。" },
  { id: "q07", typeCode: "7", title: "一想到新的计划、体验或可能性，我会很快兴奋起来。" },
  { id: "q08", typeCode: "8", title: "当场面需要有人顶上去时，我通常不会躲。" },
  { id: "q09", typeCode: "9", title: "即使我心里有意见，也常会先说“都可以”。" },
  { id: "q10", typeCode: "1", title: "如果一件事还能更好，我会忍不住继续修、继续改。" },
  { id: "q11", typeCode: "2", title: "被人需要会让我觉得自己是有价值的。" },
  { id: "q12", typeCode: "3", title: "比起反复谈感受，我更习惯先把结果做出来。" },
  { id: "q13", typeCode: "4", title: "当生活太普通、太重复时，我会觉得少了点意义。" },
  { id: "q14", typeCode: "5", title: "比起立刻参与，我更习惯先观察、理解、再行动。" },
  { id: "q15", typeCode: "6", title: "面对不确定时，我会本能地寻找可靠的人、规则或依据。" },
  { id: "q16", typeCode: "7", title: "如果一件事让我感到压抑或受限，我会想办法换条路。" },
  { id: "q17", typeCode: "8", title: "我不喜欢被控制、被试探，或被别人拿捏。" },
  { id: "q18", typeCode: "9", title: "我不喜欢高张力的冲突，会本能地想缓和或回避。" },
  { id: "q19", typeCode: "1", title: "我对“应该怎么做”通常有比较清楚的标准。" },
  { id: "q20", typeCode: "2", title: "我不太擅长直接说“我也需要你来照顾我”。" },
  { id: "q21", typeCode: "3", title: "我会留意自己是否在进步、是否被认可。" },
  { id: "q22", typeCode: "4", title: "我常能感受到别人不一定注意到的细腻情绪。" },
  { id: "q23", typeCode: "5", title: "我不喜欢别人突然侵入我的时间、精力或边界。" },
  { id: "q24", typeCode: "6", title: "我对风险和漏洞的敏感度通常比别人高。" },
  { id: "q25", typeCode: "7", title: "我会同时对很多可能性感兴趣，不太想太早收束。" },
  { id: "q26", typeCode: "8", title: "当我在乎的人被冒犯或被欺负，我会很想站出来保护。" },
  { id: "q27", typeCode: "9", title: "我常把别人的事、大家的节奏放在前面，自己的优先级反而靠后。" },
  { id: "q28", typeCode: "1", title: "就算没人要求，我也会想把事情做对、做好、做完整。" },
  { id: "q29", typeCode: "2", title: "当我的付出没有被看见时，我心里会有点委屈。" },
  { id: "q30", typeCode: "3", title: "如果一直没有成绩、没有进展，我会容易怀疑自己的价值。" },
  { id: "q31", typeCode: "4", title: "我会希望自己被真正理解，而不是被简单归类。" },
  { id: "q32", typeCode: "5", title: "当一个问题还没想明白前，我不想轻易表态。" },
  { id: "q33", typeCode: "6", title: "即使表面镇定，我心里也常会先做最坏打算。" },
  { id: "q34", typeCode: "7", title: "我不太喜欢长时间停留在沉重、无聊或痛苦的感受里。" },
  { id: "q35", typeCode: "8", title: "我习惯直接、明确地表达立场，而不是拐弯抹角。" },
  { id: "q36", typeCode: "9", title: "平稳、舒服、没有太多拉扯的状态对我很重要。" },
  { id: "q37", typeCode: "1", title: "我常在心里纠正自己：这里不够好，那样不够对。" },
  { id: "q38", typeCode: "2", title: "我会用照顾、帮忙、体贴来表达感情。" },
  { id: "q39", typeCode: "3", title: "我通常知道怎样让自己显得专业、可靠、有竞争力。" },
  { id: "q40", typeCode: "4", title: "有时候我会反复咀嚼一种情绪或一段关系带来的感受。" },
  { id: "q41", typeCode: "5", title: "我会因为掌握知识、结构或原理而感到安心。" },
  { id: "q42", typeCode: "6", title: "一旦认定一个人或团队值得信任，我会很愿意长期支持。" },
  { id: "q43", typeCode: "7", title: "就算现实有点麻烦，我也会先去想还有什么更有趣的出口。" },
  { id: "q44", typeCode: "8", title: "我宁可自己掌握主动权，也不想把命运交给别人。" },
  { id: "q45", typeCode: "9", title: "我明明心里有想法，却可能拖到很后面才真正表达或行动。" },
  { id: "q46", typeCode: "1", title: "当别人没有原则、没有边界或不讲规则时，我容易不耐烦。" },
  { id: "q47", typeCode: "2", title: "我很在意关系里的温度、回应和彼此之间的靠近感。" },
  { id: "q48", typeCode: "3", title: "为了达到目标，我可以很快调整自己的状态和表现方式。" },
  { id: "q49", typeCode: "4", title: "我既渴望靠近别人，又会担心自己和别人始终隔着一点距离。" },
  { id: "q50", typeCode: "5", title: "情绪太密集、人际太黏，会让我想往后退一点。" },
  { id: "q51", typeCode: "6", title: "我既希望安全稳定，又会反复确认这份安全是不是真的可靠。" },
  { id: "q52", typeCode: "7", title: "我天然想把生活过得有趣、丰富、不被困住。" },
  { id: "q53", typeCode: "8", title: "在冲突里，我往往更容易变得强硬，而不是退让。" },
  { id: "q54", typeCode: "9", title: "我很容易顺着环境走，避免把气氛弄僵。" },
] as const

function createScaleOptions(questionId: string, typeCode: string) {
  return ENNEAGRAM_SCALE.map((label, index) => ({
    id: `${questionId}_option_${index + 1}`,
    label,
    value: {
      [typeCode]: index + 1,
    },
  }))
}

const enneagramQuestions: QuizRuntimeConfig["questions"] = enneagramQuestionBank.map((question) => ({
  id: question.id,
  type: "single_choice",
  title: question.title,
  options: createScaleOptions(question.id, question.typeCode),
}))

const enneagramResultMap: Record<string, QuizResultDefinition> = {
  "1": {
    key: "1",
    dimensionKey: "1",
    typeCode: "1",
    title: "1 型改革者",
    subtitle: "Reformer · 完美主义者",
    nickname: "标准校准者",
    alias: "完美主义者",
    summary:
      "你通常不是为了“显得厉害”而较真，而是真心希望事情更对、更稳、更像样。你对标准、边界和责任有天然敏感度，看到明显的失误、浪费或不合理，会忍不住想修正。",
    overview: "你更容易从“怎么才算对”“怎样才算像样”出发理解世界，因此对秩序、原则和改进会天然上心。",
    firstImpression: "认真、可靠、讲原则，容易被人视为会主动把事情校正到位的人。",
    strengthSummary: "你的优势在于校准、把关、优化与让事情回到正确轨道。",
    blindSpotSummary: "当外界混乱又低标准时，你可能会先进入批判和绷紧，而忽略自己的情绪成本。",
    relationshipStyle: "你会用认真、负责、替对方考虑周全来表达在意，但也可能因为标准过高而让关系有一点紧。你不是不温柔，只是常把“应该更好”放在前面。",
    workStyle: "你适合规则明确、质量重要、能持续优化的场景。你往往能发现漏洞、压住粗糙、维持秩序，是团队里很可靠的校准者与把关者。",
    stressMode: "当事情失控、环境混乱、他人不负责时，你会更容易变得苛刻、紧绷、批判，先盯着问题而不是情绪。",
    growthAdvice: "允许自己从“必须完美”退一步，进入“已经足够好，可以先推进”。你真正需要的不是更严厉地逼自己，而是把正确感和松弛感重新放在一起。",
    posterTags: ["标准感", "责任感", "校准力"],
    highlights: [
      "很难对明显错误视而不见",
      "事情不对劲时会自然想修正",
      "对原则、边界和责任有天然敏感度",
    ],
    strengths: ["发现问题快", "做事有边界感", "在混乱里能保持标准"],
    blindSpots: ["容易先看到不足", "对自己和别人都偏严格", "松弛感不够时容易紧绷"],
    relationshipNotes: ["会用负责和周全表达爱", "在关系里重视原则和稳定", "被敷衍或失约时容易上火"],
    workNotes: ["适合把关、校准、优化流程", "能维护规则和品质", "对粗糙与漏洞很敏感"],
    stressNotes: ["事情失控时更容易批判", "环境混乱会推高紧绷感", "情绪常被正确感压住"],
    growthNotes: ["把“更好”改成“先完成”", "允许自己不完美也值得被接纳", "正确感和松弛感可以同时存在"],
    shareCopy: "你不是太挑剔，你只是很难对“不对劲”装作没看见。",
    heroTitle: "你当前最接近的驱动力模式是 1 型改革者",
    coreMotivation: "想成为一个正确、可靠、有原则的人",
    coreFear: "害怕自己犯错、失控、失格，或成为“不够好的人”",
    centerLabel: "行动中心",
    stressDirection: "4",
    growthDirection: "7",
    posterQuote: "你不是太挑剔，你只是很难对“不对劲”装作没看见。",
  },
  "2": {
    key: "2",
    dimensionKey: "2",
    typeCode: "2",
    title: "2 型助人者",
    subtitle: "Helper · 给予者",
    nickname: "关系供暖者",
    alias: "给予者",
    summary:
      "你很容易先看到别人缺什么、难受什么、需要什么。你擅长靠近、照顾、安抚和支持，也常常在“被需要”的感觉里确认自己的价值。",
    overview: "你对关系温度和他人需求很敏感，常常比别人更早一步去补位、去照顾、去靠近。",
    firstImpression: "热心、会照顾人、很有温度，容易让人觉得被接住。",
    strengthSummary: "你擅长经营关系、照顾情绪和把爱意变成具体行动。",
    blindSpotSummary: "当自己的需要长期得不到回应时，你可能会一边付出一边失落，却不容易直接说出口。",
    relationshipStyle: "你会主动表达关心，记得细节、情绪和需求，关系温度通常来自你的经营。但当自己的需要长期得不到回应时，你也容易委屈，只是未必会直接说。",
    workStyle: "你适合有人际连接、服务、支持、协调、辅导成分的环境。你擅长让别人觉得被理解、被照顾、被接住。",
    stressMode: "当付出没有回响时，你可能会更用力地给、更多地介入，甚至在心里累积“为什么没人看见我”的失落。",
    growthAdvice: "你不需要靠不断有用，才能换来被爱。比起继续猜别人的需求，更重要的是学会把自己的感受和需要也放上台面。",
    posterTags: ["温度感", "被需要", "关系连接"],
    highlights: ["很会先看到别人的需要", "容易通过照顾表达爱", "被需要时会确认自己的价值"],
    strengths: ["共情力强", "关系经营感好", "会把关心落到行动上"],
    blindSpots: ["不擅长先表达自己的需要", "容易把委屈留在心里", "付出失衡时会累积失落"],
    relationshipNotes: ["会记得细节和情绪变化", "主动靠近与安抚别人", "也需要被认真回应"],
    workNotes: ["适合服务、协调、支持型场景", "能让团队感觉被照顾", "常在关系位上发挥价值"],
    stressNotes: ["回应不足时会更用力付出", "容易陷入“为什么没人看见我”", "介入过多会透支自己"],
    growthNotes: ["练习直接说出自己的需要", "把被爱和“有用”分开", "先照顾好自己再继续照顾别人"],
    shareCopy: "你表达爱的方式，往往不是说出口，而是提前替别人想到。",
    heroTitle: "你当前最接近的驱动力模式是 2 型助人者",
    coreMotivation: "想通过付出、连接和照顾，成为一个被爱、被看见、对别人重要的人",
    coreFear: "害怕自己不被需要、不被爱，或者自己的存在没有被珍惜",
    centerLabel: "情感中心",
    stressDirection: "8",
    growthDirection: "4",
    posterQuote: "你表达爱的方式，往往不是说出口，而是提前替别人想到。",
  },
  "3": {
    key: "3",
    dimensionKey: "3",
    typeCode: "3",
    title: "3 型成就者",
    subtitle: "Achiever · 实干者",
    nickname: "结果推进者",
    alias: "实干者",
    summary:
      "你天然会把注意力放在结果、效率、表现和目标感上。你知道怎样把自己调整到“能推进、能完成、能拿成绩”的状态，也希望自己的努力能被看见。",
    overview: "你会自然地追求有成果、有进展、有认可的状态，并擅长把自己调到能推进事情的频道。",
    firstImpression: "能干、利落、有目标感，容易给人“很会成事”的印象。",
    strengthSummary: "你的优势在于推进、达成、适应目标变化与快速进入高效率状态。",
    blindSpotSummary: "当你过度把价值绑定在成果上时，容易忽略自己的真实疲惫与脆弱。",
    relationshipStyle: "你往往会先展示自己稳定、能干、靠谱的一面，不太习惯在关系里显露脆弱或混乱。你希望自己是让人放心、值得肯定的存在。",
    workStyle: "你适合节奏快、目标清晰、能看见结果的环境。你擅长推进项目、对齐标准、调整表现方式，让自己尽快进入“能成事”的状态。",
    stressMode: "当进展停滞、反馈不足、竞争变强时，你可能会更在意效率、外在表现和控制感，不太允许自己慢下来。",
    growthAdvice: "真正稳的价值感，不只来自表现，也来自你在没有成绩滤镜时依然愿意诚实面对自己。允许自己在关系里不那么“完美上场”，反而会更轻松。",
    posterTags: ["结果感", "效率", "表现力"],
    highlights: ["会自然关注结果与效率", "知道怎样让自己看起来专业可靠", "很在意有没有成绩与认可"],
    strengths: ["推进力强", "目标感清晰", "适应环境和角色变化很快"],
    blindSpots: ["容易把价值绑在成绩上", "不习惯暴露脆弱", "停滞时更容易自我怀疑"],
    relationshipNotes: ["常先展示靠谱的一面", "渴望被肯定与欣赏", "关系里未必第一时间展露真实疲惫"],
    workNotes: ["适合目标导向、节奏快的环境", "会自然进入竞争和推进模式", "懂得调整状态去拿结果"],
    stressNotes: ["进展变慢时会更绷紧", "更在意外部反馈", "容易压抑真实感受继续向前"],
    growthNotes: ["把“有价值”从“有成绩”里拆出来", "练习在关系里不只展示强项", "允许自己慢一点也不代表失败"],
    shareCopy: "你不是只爱赢，你只是太习惯用结果证明自己值得。",
    heroTitle: "你当前最接近的驱动力模式是 3 型成就者",
    coreMotivation: "想成为一个有价值、有成绩、值得被认可的人",
    coreFear: "害怕失败、无用、被忽视，或一旦没成果就失去价值感",
    centerLabel: "情感中心",
    stressDirection: "9",
    growthDirection: "6",
    posterQuote: "你不是只爱赢，你只是太习惯用结果证明自己值得。",
  },
  "4": {
    key: "4",
    dimensionKey: "4",
    typeCode: "4",
    title: "4 型个性者",
    subtitle: "Individualist · 浪漫者",
    nickname: "真实感捕手",
    alias: "浪漫者",
    summary:
      "你很在意自己的感受有没有被认真对待，也很在意自己是不是一个真实、独特、有内在质地的人。你很容易被意义感、情绪深度和身份认同的问题打动。",
    overview: "你会自然地追问“我是谁”“这段关系对我意味着什么”“这样活着够不够真实”，因此对感受和意义格外敏感。",
    firstImpression: "有辨识度、敏感、重感受，容易给人细腻而独特的印象。",
    strengthSummary: "你的优势在于感受力、审美与真实表达，能看到别人不容易说出的细腻层次。",
    blindSpotSummary: "当你过度沉浸在失落、差距或不被理解的感觉里，容易拉长内耗周期。",
    relationshipStyle: "你很在意被理解、被看见、被认真感受。关系里你不太满足于“差不多”，会更期待深度、真实和情绪上的共鸣，也因此更容易感受到落差。",
    workStyle: "你适合允许表达、创意、审美、意义感和个人风格被看见的场景。你往往不是最快的执行者，却很可能是最能让作品有质感的人。",
    stressMode: "当关系失落、现实普通、表达受限时，你可能会更容易沉进情绪、拉开距离，反复感受“我是不是始终和别人不一样”。",
    growthAdvice: "真实感不只来自强烈感受，也来自你能把感受转化成行动、作品和稳定生活。你不需要一直等被完全理解，才允许自己开始向前走。",
    posterTags: ["真实感", "情绪深度", "独特性"],
    highlights: ["很在意自己是否足够真实独特", "容易被意义感和情绪深度打动", "对关系里的落差很敏感"],
    strengths: ["感受力细腻", "表达有质感", "审美和意义感强"],
    blindSpots: ["容易沉浸在情绪里", "对普通与重复更难忍受", "不被理解时会拉长内耗"],
    relationshipNotes: ["期待深度共鸣和被理解", "不满足于表面连接", "容易放大关系中的落差感"],
    workNotes: ["适合创意、表达与审美相关场景", "重视个人风格和意义感", "更在乎作品有没有灵魂"],
    stressNotes: ["失落时会更抽离或内耗", "普通和重复会削弱能量", "容易反复咀嚼关系感受"],
    growthNotes: ["把感受转化成稳定行动", "不必等完全理解才开始", "允许自己既真实也落地"],
    shareCopy: "你不是太敏感，你只是很难对“没感觉”的生活假装满意。",
    heroTitle: "你当前最接近的驱动力模式是 4 型个性者",
    coreMotivation: "想确认自己是真实的、独特的、被深刻理解的",
    coreFear: "害怕平庸、空洞、被误解，或自己的感受不被认真看见",
    centerLabel: "情感中心",
    stressDirection: "2",
    growthDirection: "1",
    posterQuote: "你不是太敏感，你只是很难对“没感觉”的生活假装满意。",
  },
  "5": {
    key: "5",
    dimensionKey: "5",
    typeCode: "5",
    title: "5 型观察者",
    subtitle: "Investigator · 探索者",
    nickname: "边界研究员",
    alias: "探索者",
    summary:
      "你习惯先理解，再靠近；先看清，再投入。你对知识、边界、独立性和能量管理有天然需求，不喜欢被情绪、人际或混乱环境一下子耗空。",
    overview: "你会自然地通过观察、理解和建立边界来保护自己，因此比起立刻参与，你更在意自己有没有准备好。",
    firstImpression: "冷静、清醒、有边界感，容易让人觉得你先想明白才会认真投入。",
    strengthSummary: "你的优势在于分析、抽离复杂度、独立思考与保持心理空间。",
    blindSpotSummary: "当你过度退到观察位，可能会让重要关系和现实参与感一起变淡。",
    relationshipStyle: "你通常需要空间感、节奏感和边界感。你不是不在乎，而是不喜欢被过度黏连、被情绪裹挟，或在还没准备好时被迫回应。",
    workStyle: "你适合系统性、研究型、需要长期思考与独立判断的环境。相比被频繁打断，你更适合在相对完整的空间里把问题想透。",
    stressMode: "当信息过载、人际过密、外界索取太强时，你会更容易抽离、退后、关闭感受，优先守住自己的能量边界。",
    growthAdvice: "理解当然重要，但真正的掌握也来自参与。你不必等自己完全准备好，才允许自己进入关系和现实。适度暴露在真实互动里，反而会让你更稳。",
    posterTags: ["独处需求", "边界感", "理解先行"],
    highlights: ["需要足够多的独处和心理空间", "更习惯先观察理解再行动", "会因为掌握知识与结构而感到安心"],
    strengths: ["分析力强", "独立思考能力好", "擅长给混乱建立结构"],
    blindSpots: ["容易退到旁观位", "人际太密时会本能抽离", "准备过度会拖慢参与"],
    relationshipNotes: ["需要空间和边界感", "不喜欢被情绪或黏连裹挟", "慢热但一旦投入会比较稳定"],
    workNotes: ["适合研究、系统、深度思考型任务", "需要较完整的独立工作空间", "擅长理解复杂问题"],
    stressNotes: ["过载时会先抽离", "优先守住能量边界", "可能关闭感受减少消耗"],
    growthNotes: ["不必等完全准备好才开始", "适度参与能让理解更落地", "让身体和现实也一起在线"],
    shareCopy: "你不是冷淡，只是很认真地守着自己的能量边界。",
    heroTitle: "你当前最接近的驱动力模式是 5 型观察者",
    coreMotivation: "通过理解与掌握，维持独立与不被消耗的状态",
    coreFear: "无能、空心、被侵入、被过度索取",
    centerLabel: "思维中心",
    stressDirection: "7",
    growthDirection: "8",
    posterQuote: "你不是冷淡，只是很认真地守着自己的能量边界。",
  },
  "6": {
    key: "6",
    dimensionKey: "6",
    typeCode: "6",
    title: "6 型忠诚者",
    subtitle: "Loyalist · 怀疑者",
    nickname: "风险预演者",
    alias: "怀疑者",
    summary:
      "你很在意稳定、安全、可靠和有没有足够可信的依据。你往往不是天生悲观，而是会自然地先看到风险、漏洞和不确定性，然后努力让自己站在更稳的位置。",
    overview: "你会自然地在心里做风险预演，希望在真正出状况前就先找到更稳妥的抓手。",
    firstImpression: "谨慎、靠谱、有责任感，也容易给人“会提前想到风险”的印象。",
    strengthSummary: "你的优势在于防风险、查漏洞、提前预案和对关系或团队的长期投入。",
    blindSpotSummary: "当安全感主要依赖外部确认时，你容易在反复确认和自我怀疑之间来回拉扯。",
    relationshipStyle: "你在关系里往往更看重可靠、守约、有没有回应以及对方值不值得信任。你不是不敢投入，而是在投入前会先确认这段关系是否足够稳。",
    workStyle: "你适合需要风控、复核、流程、协作责任感和长期稳定推进的环境。你能提前看到潜在问题，也很适合做体系里的守门员。",
    stressMode: "当环境模糊、反馈不稳、规则摇摆时，你会更容易反复确认、想很多、心里拉扯，甚至一边怀疑一边硬撑。",
    growthAdvice: "安全感不能只靠外部保证，也来自你对自己判断力的信任。你不需要等到零风险，才允许自己往前走一步。",
    posterTags: ["安全感", "可靠性", "风险预演"],
    highlights: ["做决定前会先想风险点", "面对不确定会寻找可靠依据", "既希望稳定又会反复确认稳定是否可靠"],
    strengths: ["风险敏感度高", "对团队和关系很忠诚", "擅长提前预案"],
    blindSpots: ["容易反复确认", "安全感波动时会内耗", "在怀疑和硬撑之间摇摆"],
    relationshipNotes: ["重视守约和可靠", "投入前会先确认值不值得信任", "被模糊回应时更容易不安"],
    workNotes: ["适合流程、风控、复核型场景", "能提前发现漏洞", "很适合做体系里的守门员"],
    stressNotes: ["规则摇摆时会更拉扯", "容易一边怀疑一边硬撑", "外部反馈不稳会放大不安"],
    growthNotes: ["训练对自己判断力的信任", "先迈小步而不是等零风险", "让安全感更多来自内部稳定"],
    shareCopy: "你不是想太多，你只是太早在脑海里替现实做了风险预演。",
    heroTitle: "你当前最接近的驱动力模式是 6 型忠诚者",
    coreMotivation: "想获得安全、支持、可依靠的结构与关系",
    coreFear: "害怕失去支持、遭遇风险、无人可依，或在关键时刻站不稳",
    centerLabel: "思维中心",
    stressDirection: "3",
    growthDirection: "9",
    posterQuote: "你不是想太多，你只是太早在脑海里替现实做了风险预演。",
  },
  "7": {
    key: "7",
    dimensionKey: "7",
    typeCode: "7",
    title: "7 型热情者",
    subtitle: "Enthusiast · 冒险家",
    nickname: "可能性点火器",
    alias: "冒险家",
    summary:
      "你会天然被新鲜感、自由度、好玩和可能性吸引。你喜欢把生活打开，不想被困在单一、沉重、没有出口的状态里。",
    overview: "你常把目光投向未来和新鲜出口，希望自己总能保留选择权与兴奋感。",
    firstImpression: "有活力、会带气氛、点子多，容易让周围的人也跟着动起来。",
    strengthSummary: "你的优势在于打开局面、发现机会、点燃气氛和快速启动新方向。",
    blindSpotSummary: "当你把自由感只放在不断切换上，深度、承诺与停留就容易变得更难。",
    relationshipStyle: "你常带来轻松、活力、点子和体验感，关系里的快乐值常常被你拉高。但当情绪变重、承诺变硬时，你也可能本能地想找出口。",
    workStyle: "你适合变化快、点子多、空间大、允许探索的场景。你对新机会、新方向、新玩法的感知很快，启动速度也常常很强。",
    stressMode: "当现实开始收紧、情绪开始变沉时，你容易靠分散注意、切换目标、寻找新刺激来回避不舒服。",
    growthAdvice: "自由不只是不断打开新选项，也包括有能力留在一个选项里，把它走深。你真正想要的，不只是更多可能，而是更完整地拥有其中一种可能。",
    posterTags: ["自由度", "新鲜感", "启动速度"],
    highlights: ["想到新计划和可能性会很兴奋", "不喜欢被困在压抑受限里", "天然想把生活过得有趣丰富"],
    strengths: ["很会打开局面", "点子多、启动快", "擅长给环境带来活力"],
    blindSpots: ["容易回避沉重情绪", "不想太早收束或承诺", "深度停留对你是练习"],
    relationshipNotes: ["会给关系带来快乐和体验感", "不喜欢长期沉重和拉扯", "承诺变硬时会想找出口"],
    workNotes: ["适合变化快、探索空间大的环境", "对新机会反应快", "擅长点燃方向和推动开始"],
    stressNotes: ["现实收紧时更想切换", "会用新刺激分散不适", "容易避开沉重而不是留在当下"],
    growthNotes: ["练习把一个选项走深", "把自由从“切换”变成“选择后仍有主体性”", "允许自己待在不舒服里一会儿"],
    shareCopy: "你看起来总在往前冲，其实是在努力不被困住。",
    heroTitle: "你当前最接近的驱动力模式是 7 型热情者",
    coreMotivation: "想保持自由、快乐、选择权和面向未来的兴奋感",
    coreFear: "害怕受限、停滞、被困住，或长时间停留在痛苦与匮乏里",
    centerLabel: "思维中心",
    stressDirection: "1",
    growthDirection: "5",
    posterQuote: "你看起来总在往前冲，其实是在努力不被困住。",
  },
  "8": {
    key: "8",
    dimensionKey: "8",
    typeCode: "8",
    title: "8 型挑战者",
    subtitle: "Challenger · 保护者",
    nickname: "主导权守护者",
    alias: "保护者",
    summary:
      "你对力量、边界、主动权和真实立场很敏感。你不喜欢被压、被控、被试探，遇到重要的人和事时，也会很自然地进入保护和主导状态。",
    overview: "你很在意自己能不能握住主导权，也不喜欢把命运和安全感轻易交到别人手里。",
    firstImpression: "直接、有存在感、不绕弯，容易让人感到你的力量和立场。",
    strengthSummary: "你的优势在于决断、保护、扛事、定调和在关键时刻顶上去。",
    blindSpotSummary: "当你只允许自己用强硬来保护安全时，别人会更难靠近你的柔软部分。",
    relationshipStyle: "你往往很直接，很少玩试探和模糊。你在意的人，会明显感受到你的护短、担当与存在感，但也可能感受到你的强势。",
    workStyle: "你适合需要决断、推动、扛事、应对冲突和整合资源的场景。你能在混乱里迅速定调，在关键时刻顶住压力。",
    stressMode: "当你感到被限制、被质疑、被拖累时，你会更容易变硬、变急、变得更不愿示弱。",
    growthAdvice: "真正稳的力量，不只来自强硬，也来自有能力让别人靠近你的柔软部分。你不需要时时刻刻都站在最前面，才算安全。",
    posterTags: ["力量感", "边界", "主导权"],
    highlights: ["不喜欢被控制、被拿捏", "重要场面里通常不会躲", "在冲突中更容易变强硬而不是退让"],
    strengths: ["扛事能力强", "决断快", "能在关键时刻保护重要的人和事"],
    blindSpots: ["强势感可能压过温度", "不容易示弱", "被限制时会更硬更急"],
    relationshipNotes: ["直接表达立场和在意", "很有护短感和担当", "模糊试探会让你不耐烦"],
    workNotes: ["适合决断与推进型环境", "能在混乱里迅速定调", "关键时刻抗压能力强"],
    stressNotes: ["被质疑或拖累时会更强硬", "不愿轻易示弱", "容易把脆弱包进强势里"],
    growthNotes: ["把柔软也纳入力量的一部分", "允许别人靠近你的真实疲惫", "不必一直站最前面才能安全"],
    shareCopy: "你不是脾气大，你只是很难接受自己被动地交出主导权。",
    heroTitle: "你当前最接近的驱动力模式是 8 型挑战者",
    coreMotivation: "想保持力量、掌控感和不被他人左右的主体性",
    coreFear: "害怕脆弱、被控制、被伤害，或在关键时刻失去主导权",
    centerLabel: "行动中心",
    stressDirection: "5",
    growthDirection: "2",
    posterQuote: "你不是脾气大，你只是很难接受自己被动地交出主导权。",
  },
  "9": {
    key: "9",
    dimensionKey: "9",
    typeCode: "9",
    title: "9 型和平者",
    subtitle: "Peacemaker · 调停者",
    nickname: "和谐缓冲器",
    alias: "调停者",
    summary:
      "你很在意环境里的平稳感、舒服感和少冲突状态。你通常能理解不同立场，也常愿意先让一步，让事情不要变得太僵。",
    overview: "你会自然地维护和谐与舒适，希望关系和环境不要陷入高张力与长期拉扯。",
    firstImpression: "温和、好相处、给人空间，容易让身边的人先放松下来。",
    strengthSummary: "你的优势在于协调、缓冲、整合不同节奏和维持整体氛围稳定。",
    blindSpotSummary: "当你总是优先维持气氛而不是表达自己时，真正的需求会慢慢被压后。",
    relationshipStyle: "你容易让人觉得温和、好相处、给人空间。你不喜欢关系里长期拉扯，但也可能因为太常顺着别人，而把自己的真正需要压后。",
    workStyle: "你适合需要协调、整合、维稳、耐心推进的环境。你能包容不同节奏，也能在紧绷的人群里起到缓冲作用。",
    stressMode: "当外界要求太多、冲突太近时，你可能会更拖延、更放空、更不想正面碰撞，表面平静，内里却在消耗。",
    growthAdvice: "和谐不等于总是退后。真正稳的关系，也容得下你的边界、偏好和不同意。你不需要先把自己变小，才能维持连接。",
    posterTags: ["和谐感", "舒服", "缓冲力"],
    highlights: ["即使有意见也常先说都可以", "平稳舒服对你很重要", "很容易顺着环境走避免气氛僵掉"],
    strengths: ["协调感强", "能缓冲紧绷氛围", "很会维持舒适和可持续"],
    blindSpots: ["容易把自己放到后面", "冲突近时会更拖延或放空", "真正的需要不容易被优先处理"],
    relationshipNotes: ["给人温和和有空间的感觉", "不喜欢长期拉扯与高张力", "太常顺着别人时会忽略自己"],
    workNotes: ["适合协调与耐心推进型环境", "能包容不同节奏", "是团队里的缓冲层"],
    stressNotes: ["要求太多时更想躲开冲突", "表面平静但内里消耗", "容易拖延和放空"],
    growthNotes: ["让不同意也能被看见", "把自己的偏好与边界提到前面", "和谐里也应该有你的存在"],
    shareCopy: "你不是没有想法，只是太习惯先让气氛保持平静。",
    heroTitle: "你当前最接近的驱动力模式是 9 型和平者",
    coreMotivation: "想维持和谐、内在平稳与关系中的可持续舒适感",
    coreFear: "害怕冲突、割裂、失去连接，或因为坚持自己而打破平衡",
    centerLabel: "行动中心",
    stressDirection: "6",
    growthDirection: "3",
    posterQuote: "你不是没有想法，只是太习惯先让气氛保持平静。",
  },
}

const ENNEAGRAM_RESULT_ORDER = ["1", "2", "3", "4", "5", "6", "7", "8", "9"] as const

export const enneagramResults = ENNEAGRAM_RESULT_ORDER.map((key) => enneagramResultMap[key])

export const enneagramRuntime: QuizRuntimeConfig = {
  meta: {
    slug: "enneagram",
    title: "九型人格测试",
    summary:
      "一套更偏向“核心驱动力”视角的九型人格测试。54 道原创中文题，帮你看见自己更接近哪一种内在动机模式，以及关系、工作和压力下的自然反应。",
    estimatedMinutes: 9,
    tags: ["九型人格", "54 题正式版", "核心驱动力", "适合保存分享长图"],
    category: "人格 / 驱动力",
  },
  runtime: {
    rendererKey: "generic",
    resultTemplateKey: "enneagram-profile",
    scoringKey: "enneagram",
  },
  presentation: {
    themeKey: "editorial-mystic",
    storyMode: true,
    screenCount: 6,
    shareCardKey: "enneagram-drive-poster",
  },
  questions: enneagramQuestions,
  results: enneagramResults,
  extensions: {
    scoring: {
      dimensions: ENNEAGRAM_DIMENSIONS.map((item) => ({ ...item })),
    },
    intro: {
      tagline: "54 题正式版，适合做“核心驱动力地图”，结果支持回看、保存与分享。",
      priceLabel: "54 题正式版",
      accessSummary: "输入购买后获得的验证码开始测试，有效期内可重复进入",
      valuePoints: ["主型 + 近邻类型判断", "关系 / 工作 / 压力方向解析", "支持导出社媒分享长图"],
      flowSteps: ["输入验证码", "完成 54 题符合度作答", "查看完整结果"],
    },
    share: {
      captionTone: "editorial",
    },
    enneagram: {
      questionsPerType: 6,
      maxScorePerType: 30,
      closeCallDelta: 2,
      wingDelta: 5,
      centers: {
        "1": "行动中心",
        "2": "情感中心",
        "3": "情感中心",
        "4": "情感中心",
        "5": "思维中心",
        "6": "思维中心",
        "7": "思维中心",
        "8": "行动中心",
        "9": "行动中心",
      },
      wingMap: {
        "1": ["9", "2"],
        "2": ["1", "3"],
        "3": ["2", "4"],
        "4": ["3", "5"],
        "5": ["4", "6"],
        "6": ["5", "7"],
        "7": ["6", "8"],
        "8": ["7", "9"],
        "9": ["8", "1"],
      },
      directions: {
        "1": { stress: "4", growth: "7" },
        "2": { stress: "8", growth: "4" },
        "3": { stress: "9", growth: "6" },
        "4": { stress: "2", growth: "1" },
        "5": { stress: "7", growth: "8" },
        "6": { stress: "3", growth: "9" },
        "7": { stress: "1", growth: "5" },
        "8": { stress: "5", growth: "2" },
        "9": { stress: "6", growth: "3" },
      },
    },
  },
}
